### ISSUE TITLE
Last image failed to fill in one row when images container are not 100% width

### ISSUE THREAD

**Issue by umhan35** [ed-lea/jquery-collagePlus#13]
Hi, you may see from the following screenshot 1. The Guess photo on the third row should be in the second row. The width of that photo (and all the other photos) are calculated 1 more pixel than expected. You can see from screenshot 2, when I change the width of the image contaoner from 485px to 484px, the Guess photo is paced to where it should be.

I'm guessing this is because we are using round function (1.9 = 2, 456.89 = 457 ) when the images container? So we are placing a little more pixel on one row. I'm not sure. I may look the code later this week but I think it's good to create an issue for this.

You may this issue live on http://chaozhi.la/

Thanks, the 2 screenshots are as follow:

screenshot 1:

![](https://f.cloud.github.com/assets/3271612/1246111/6d563a6c-2aa9-11e3-9318-4d0e4335204b.png)

screenshot 2:

![screenshot- - google chrome](https://f.cloud.github.com/assets/3271612/1246144/dc07e35c-2aa9-11e3-975d-06d75bf67367.png)

**Comment by ed-lea** [comment]
Hi,

I think the most likely reason for this is that your html has spaces. e.g.

```
<div>
    <img src="someimage.jpg" />
</div>
<div>
    <img src="someimage2.jpg" />
</div>
```

if you do it like this

```
<div><img src="someimage.jpg" /></div><div><img src="someimage.jpg" /></div>
```

if should fix the problem. Try that first and let me know.

Cheers!
Ed.

**Comment by umhan35** [comment]
I used `removeWhitespace()`. Does it do the same thing?

Also, if you try to resize the browser window of my website: chaozhi.la/, you will see the plugin works sometime but not consistent.

The problem shows up when I added the left side bar. And I use % to control the width of the sidebar and the collage area.

The following is my coffescript code:

``` coffeescript
$(document).ready ->
  $('.collage').removeWhitespace()
  $('.collage').imagesLoaded ->
    collage()

collage = () ->
  $('.collage').collagePlus(
    'fadeSpeed' : 800
    'targetHeight' : 400
    'allowPartialLastRow' : true
  )

resizeTimer = null
$(window).bind('resize', -> # set a timer to re-apply the plugin
  clearTimeout(resizeTimer) if resizeTimer
  resizeTimer = setTimeout(collage, 200)
)
```

**Comment by umhan35** [comment]
Here are 2 more screenshots of Google Chrome metrics to show the width of the browser window. Hope they help.

The width difference is less than 1px.

Thanks

screenshot 1 (not working):
![](https://f.cloud.github.com/assets/3271612/1249802/dae90e32-2ae6-11e3-8490-09cda1478e23.png)

screenshot 2 (working):
![w](https://f.cloud.github.com/assets/3271612/1249809/f4e4f800-2ae6-11e3-8b20-1540a9990a4c.png)

**Comment by ed-lea** [comment]
Hi,

When the plugin didn't appear to be working, I added the resized images widths for a row and they added up to exactly the same width as the parent div. i.e. they should have fitted but some other artefact in the HTML was breaking it.

The screenshots you have supplied though make me wonder about fractions of a pixel. I didn't think that was actually possible so I need to investigate.

Re; removewhitespace, yes that should be doing it, but it's not my code so maybe it's broken. I need to look into that too.

is this project urgent?

**Comment by umhan35** [comment]
I would say it's urgent. But you said you were moving aboard. So, I hope this issue can be solved quickly...

**Comment by umhan35** [comment]
I found a workaround solution: add `fw--;` to line 264.

**Comment by ed-lea** [comment]
Interesting, thanks. I'll look into it and add it to the code. Thanks for the support and apologies for not getting back to you sooner, I moved to another country and things got crazy busy!
