### ISSUE TITLE
Any thoughts on giving some kind of priority / random support for portrait images?

### ISSUE THREAD

**Issue by greggman** [ed-lea/jquery-collagePlus#14]
Your gallery plugin is awesome.  I was wondering how hard it would be to give some kind of support for portrait images. For example

```
+-----+---+
|     |   |
|     +---+
|     |   |
|     +---+
|     |   |
+-----+---+
```

Lots of images are portrait, especially with smartphones. As such the fact that the current gallery only does rows and then fits images into those rows means portrait images are almost always very small.

Thoughts?

Ideally it would make collages where there are often no lines that go all the way across or down the screen.

okay:

```
+----+---+-----+
|    |   |     |
+--+-+--++-----+
|  |    |      |
+--++---+--+---+
|   |      |   |
+---+------+---+
```

okay:

```
+---+---+---+
|   |   |   |
|   +---+   |
+---+   |   |
|   |   +---+
+---+   |   |
|   |   +---+
|   +---+   |
|   |   |   |
+---+---+---+
```

best:

```
+------+------+
|        |    |
|        +----+
|        |    |
+----+---+-+--+
|    |     |  | 
|    |     +--+ 
+----+     |  | 
|    |     |  | 
+----+-----+--+
```

**Comment by mrivasa** [comment]
I second that.  It will be a good addition to an already nice plugin.

**Comment by ed-lea** [comment]
sorry for the delay in my reply, I've been moving to another country and haven't had a chance to look at the plugin. 

Well, your suggestion is quite a challenge! the diagrams you shared are really helpful and I totally get what you're suggesting. That's quite a hard problem to solve. I'll have a think about it. It almost borders on being another plugin :)

**Comment by ed-lea** [comment]
Actually, just stumbled across this plugin, is this what you meant? http://vnjs.net/www/project/freewall/

**Comment by greggman** [comment]
yea, I saw that after I posted this. I had trouble getting it to work if each item is not a multiple of grid size.

**Comment by ed-lea** [comment]
oh interesting. I haven't actually tried it, just looked at the examples. I'll give it a go and see if there is an opportunity to support that functionality.

**Comment by ed-lea** [comment]
after looking into it, I think the fact that there are other plugins doing this means it's not worth adding to CollagePlus due to the additional weight. Would rather keep it small and focused for the time being. Also easier to support.
