### ISSUE TITLE
Scrollbar moves the last image of the row to the next row

### ISSUE THREAD

**Issue by matteoraf** [ed-lea/jquery-collagePlus#23]
This is happening on 
-Firefox on Mac OS.
-Chrome on Windows
-IE on Windows

Works fine on Safari and Chrome on Mac

I've put the gallery inside a box. 
You can see an example at http://www.villareginateodolinda.it/#!gallery
What happens is that the vertical scrollbar takes the space that was designated for the imgs. Thus the last image of the row is forced to move one row down.

**Comment by matteoraf** [comment]
I solved it modifying this line:
'albumWidth'      : (this.width()-15),

But it would be nice to find a better way, because now there is a big empty area on the right.

**Comment by ed-lea** [comment]
does this happen to you if you try the examples? http://collageplus.edlea.com/example.html

**Comment by matteoraf** [comment]
No, because in your example the container is free to expand its height as much as necessary.
Try to give to your .Collage class a fixed height and overflow-y:scroll and the problem comes up.

**Comment by ed-lea** [comment]
you should wrap your .Collage element in another element and size that one to scroll. i.e.

```
<div style="width:500px;height: 300px;overflow-y: scroll;">
    <div class="Collage">
    .... your collage images
</div>
```

instead of giving .Collage a height. I think this is expected behaviour if you give .Collage a scrollbar.
