### ISSUE TITLE
multiple instances

### ISSUE THREAD

**Issue by haheute** [ed-lea/jquery-collagePlus#24]
It seems, that multiple instances are not calculated separated for each instance. (I have 5 divs with class="Collage" and try to have separated collages) --> hope you can see it on the screenshot

![collageplus-multiple](https://f.cloud.github.com/assets/5753419/1589566/f7623746-5273-11e3-9f07-f7924c312d5a.jpg)

**Comment by rednakse** [comment]
Subscribe to the issue. I could not decide.
Temporarily solved the problem this way:

```
$('.Collage').each(function(){ 
    $(this).collagePlus({
    'targetHeight': 200,
    'direction'   : 'vertical',
    'allowPartialLastRow'   : false
    });
});
```

**Comment by haheute** [comment]
so easy.. it works. thank you.
