### ISSUE TITLE
Add parameter to enable last row to be full width or not

### ISSUE THREAD

**Issue by ed-lea** [ed-lea/jquery-collagePlus#4]
The most dominant property of the plugin is the width of the parent grid, i.e. it will always force the width of the parent grid and override the target height. Target height is really just a guide size and not a fixed value. This is because to fit the images to the exact width, the height must be adjusted to maintain aspect ratio. The problem usually happens when the image (or couple of images) are the last in the row so there is not really enough to fill the width without making those images much bigger. For example, a 400px wide image might be stretched to 1000px wide if it is the only image available to that row.

Adding a setting will enable devs to choose appropriate behaviour

`var allowPartialLastRow = true : false`

**Comment by scottdonald** [comment]
I was curious if you had a time-frame for making this update? I have a project I'd like to use this on but it's kinda funky if one or two items on the last row are huge. 

Thanks for this great script!

**Comment by ed-lea** [comment]
@scottdonald I have a working version on this branch https://github.com/ed-lea/jquery-collagePlus/blob/lastrowfix/jquery.collagePlus.js but I'm still testing it. Feel free to grab that code and give it a try. Just add `'allowPartialLastRow' : true` parameter to where you call the plugin from.

**Comment by scottdonald** [comment]
Just gave this a quick try and it seems to work great, thanks! I'll let you know if we find any issues as we test.

**Comment by ed-lea** [comment]
Committed to master now and will up the version tag. Any probs, let me know.
