### ISSUE TITLE
Set number of rows.

### ISSUE THREAD

**Issue by azaroabiku** [ed-lea/jquery-collagePlus#47]
Hi.
This module works fine for me except one issue:  I cannot set the number of rows for the images. For example I have 10 images and want to display them in 3 rows so they fit in the container.
or for example 5 images in 1 row.
Is it hard to modify the library so it works with that functionality?

thanks for help in advance

**Comment by skerbis** [comment]
Did someone find a solution, where to deine the number of rows?

**Comment by ed-lea** [comment]
The plugin could not work like this as the main factor for the number of images is the targetHeight of each image. I would be possible to make a plugin that would work like that, but it's not something this one would support.
