### ISSUE TITLE
Loader/spinner

### ISSUE THREAD

**Issue by adrianbj** [ed-lea/jquery-collagePlus#6]
A page with lots of large images can often take a while to load since all images seem to need to be loaded before any are shown. Any chance you could add something to indicate that the images are loading? Thanks!

**Comment by ed-lea** [comment]
yes, this is something I will certainly add.

The thing with this plugin is that all images need to be loaded in order to get the image sizes (and hence calculate the grid)

**Comment by adrianbj** [comment]
Couldn't the script grab the width and height values from the img tag, assuming they have been set?

**Comment by ed-lea** [comment]
if you already know the image width and height (i.e. it's in your html) then you should calculate this grid layout when you generate the HTML i.e. server side.

but it would be possible to adapt the plugin to do this. I'll look into it.

**Comment by adrianbj** [comment]
Agreed, server-side would be a better option in many cases, but your plugin is such a simple way to add this functionality to a page, it would be nice to improve the rendering speed when possible (ie image dimensions already known).

Thanks for considering.

**Comment by ed-lea** [comment]
ok, then it's something I'll certainly add in.

**Comment by ed-lea** [comment]
I just realised that it would already work before waiting to load all images. [This part of the plugin](https://github.com/ed-lea/jquery-collagePlus/blob/master/jquery.collagePlus.js#L86) will grab the sizes. To see it in action, don't wrap the plugin call with `$(window).load(function () {`

The caveat is that all images require image size in the tag. Also, the fade in effect doesn't wait for the image to load, this is what I am working on now.

**Comment by adrianbj** [comment]
Seems to be working great without the $(window).load

Thanks!

**Comment by arkan** [comment]
I tried to don't warp the plugin call with `$(window).load(function () {` but it doesn't work.

Any plan to support this really out of the box?

**Comment by ed-lea** [comment]
is this demo working for you? http://collageplus.edlea.com/example-size-in-tag.html
