### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by colonna-mike** [ed-lea/jquery-collagePlus#62]
Is there a limit on how small  jquery-collage-plus will shrink a image to fix the grid?

I'm using it in a mobile phone app and for large devices it working well but for smaller phones when in portrait mode the image are all in a vertical row, when I change the orientation to landscape the images loads the way I expected them to ( wider width I'm guessing ) .

Here how I have it setup:

``` javascript
$(selector).collagePlus({
          'targetWidth':$(document).width(),
          'direction': 'horizontal', 
          'effect' : 'effect-4',
         'allowPartialLastRow': false
    });
```

Any clarification on how images are re-sized would be great..

**Comment by haheute** [comment]
I could not find the option `targetWidth`. perhaps you must use `targetHeight` ("the ideal height you want your images to be") .. (?)

**Comment by colonna-mike** [comment]
@haheute yea I tried that but it just cut the images off, it did not size them?   I know height is just a references point but it's not  working  :-(

**Comment by colonna-mike** [comment]
@haheute I went back and looked and you are right there is no targetWidth, I removed that and set the height and it worked thanks for pointing that out!
