### ISSUE TITLE
Using Lightbox with CollagePlus

### ISSUE THREAD

**Issue by Modernized** [ed-lea/jquery-collagePlus#7]
Is there any way in which I can use lightbox with CollagePlus?
Whenever I try to put an "a" tag around an "img" tag the picture doesn't show up.

**Comment by ed-lea** [comment]
can't you make the `<img>` element the clickable element to launch lightbox?

Also, wrapping the image in another element shouldn't affect the plugin.

**Comment by dubblebee** [comment]
I have used a lightbox called Fresco with CollagePlus which is working great.

http://www.frescojs.com/

Include the Fresco JS & CSS in your head tag.
Then when listing your images add a class="fresco" and if you want a gallery view also add data-fresco-group="name" to your image tags

**Comment by josegmece** [comment]
dubblebee and  Ed-lea  ! Hey mens thank you so much ! works for what i wanted, you save a lot of dev time !!!!!!
and again thank you!!!!!
